### ISSUE TITLE
Remove docs from website

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser.github.io#13]
Was thinking about moving the docs for some place we can change them more easily:

1. GitHub Wiki
2. Gitbook (like https://filebrowser.gitbook.io/docs)
3. Just put on the README

We don't actually have many docs. It's just the docker info, the custom branding and quick guide explaining how to use this.

I'm leaning towards the third option because it's really not that many docs.

We'd keep the website of course as a good entry point.

@1138-4EB @Equim-chan what do you think?

**Comment by hacdias** [comment]
Or even just use the README since it's not that much docs: the CLI has --help. We just need to give info about features **and** some simple guides to make an installation work.

**Comment by 1138-4EB** [comment]
I think that options 1. and 2. are quite similar to the current solution. In the end, sources are markdown files in a git repo. Certainly, Jekyll/Hugo can be used to offer an alternative visualization of a GitHub Wiki. So, I don't really mind which solution to use.

However, I would not put everything in a single file.

**Comment by hacdias** [comment]
@1138-4EB hmm, yes, I was taking a look and they are actually more than I thought. By the way, I bought the domain filebrowser.xyz (it was really cheap :O) and I had an idea:

1. filebrowser.xyz -> a simple entry page showing some features and some links (like right now)
2. docs.filebrowser.xyz -> gitbook!

Also thought of adding [community](https://github.com/filebrowser/community) docs to that page so we had all the docs centralized.

**Comment by hacdias** [comment]
@1138-4EB GitBook allows us to use their interface to edit and it is really easy to use. It is sync'ed with filebrowser/docs so you can also update the files there. Yes, they use JavaScript but the docs are beautiful and really simple to use.

I haven't done much but please take a look: https://docs.filebrowser.xyz
